#include "dbat/db/consts/affflags.h"


/* AFF_x */
/* Many are taken from the SRD under OGL, see ../doc/srd.txt for information */
const char *affected_bits[NUM_AFF_FLAGS+1] =
{
  "\0", /* DO NOT REMOVE!! */
  "BLIND",
  "INVIS",
  "DET-ALIGN",
  "DET-INVIS",
  "DET-MAGIC",
  "SENSE-LIFE",
  "WATWALK",
  "BARRIER",
  "GROUP",
  "CURSE",
  "INFRAVISION",
  "POISON",
  "WEAKENED",
  "PROT-GOOD",
  "SLEEP",
  "NO_TRACK",
  "UNDEAD",
  "STONED",
  "SNEAK",
  "HIDE",
  "UNUSED",
  "CHARM",
  "FLYING",
  "WATER-BREATH",
  "ANGELIC",
  "ETHEREAL",
  "MAGICONLY",
  "NEXTPARTIAL",
  "NEXTNOACT",
  "STUNNED",
  "TAME",
  "CDEATH",
  "SPIRIT",
  "STONESKIN",
  "SUMMONED",
  "CELESTIAL",
  "FIENDISH",
  "FIRESHIELD",
  "LOW_LIGHT",
  "ZANZOKEN",
  "KO",
  "MIGHT",
  "FLEX",
  "GENIUS",
  "BLESS",
  "BURNT",
  "BURNED",
  "MBREAK",
  "HASS",
  "FS",
  "PARALYZE",
  "INFUSED",
  "ENLIGHT",
  "FROZOWNED",
  "FIRESHIELD",
  "ENSNARED",
  "HAYASA",
  "PURSUED",
  "WITHERED",
  "HYDROZAP",
  "POSITION",
  "SHOCKED",
  "METAMORPH",
  "HEALING-GLOW",
  "ALGIZ RUNE",
  "OAGAZ RUNE",
  "WUNJO RUNE",
  "PURISAZ RUNE",
  "ASHED",
  "PUKED",
  "LIQUEFIED",
  "SHELLED",
  "IMMUNITY",
  "SPIRITCONTROL",
  "\n"
};
