#include "dbat/db/consts/constates.h"


/* CON_x */
const char *connected_types[NUM_CON_TYPES+1] = {
  "Playing",
  "Disconnecting",
  "Get name",
  "Confirm name",
  "Get password",
  "Get new PW",
  "Confirm new PW",
  "Select sex",
  "Select class",
  "Reading MOTD",
  "Main Menu",
  "Get descript.",
  "Changing PW 1",
  "Changing PW 2",
  "Changing PW 3",
  "Self-Delete 1",
  "Self-Delete 2",
  "Disconnecting",
  "Object edit",
  "Room edit",
  "Zone edit",
  "Mobile edit",
  "Shop edit",
  "Text edit",
  "Config edit",
  "Select race",
  "Assembly Edit",
  "Social edit",
  "Trigger Edit",
  "Race help",
  "Class help",
  "Query ANSI",
  "Guild edit",
  "Reroll stats",
  "iObject Edit",
  "Level Up",
  "Qstats",
  "Hair Length",
  "Hair Color",
  "Hair Style",
  "Skin Color",
  "Eye Color",
  "Start Q1",
  "Start Q2",
  "Start Q3",
  "Start Q4",
  "Start Q5",
  "Start Q6",
  "Start Q7",
  "Start Q8",
  "Start Q9",
  "Start Q10",
  "House Edit",
  "Alpha",
  "Alpha 2",
  "Android Menu",
  "Help Edit",
  "Get User",
  "Get Email",
  "Get UMenu",
  "Confirm User",
  "Dist. Feature",
  "Height/Weight",
  "Aura",
  "Bonus/Neg",
  "Bonus/Neg",
  "News Edit",
  "Racial Pref",
  "Player Obj Edit",
  "Align Menu",
  "Skills Menu",
  "User Title",
  "Genome Selection",
  "\n"
};
