?start: expr

?expr: expr "or" term       -> or_expr
     | term

?term: term "and" factor    -> and_expr
     | factor

?factor: "!" factor         -> not_expr
       | function_call
       | "(" expr ")"

function_call: NAME "(" [arguments] ")"
arguments: argument ("," argument)*
?argument: SIGNED_NUMBER   -> number
         | ESCAPED_STRING  -> string

%import common.CNAME -> NAME
%import common.SIGNED_NUMBER
%import common.ESCAPED_STRING
%import common.WS
%ignore WS