dynaconf_merge = true

[mssp]
NAME = "Dragon Ball: Advent Truth"
CODEBASE = "CircleMUD"
FAMILY = "DikuMUD"

[portal.networking]
telnet = 1280
telnets = 1281
ssh = 1282
game_url = "https://dbat.mushhaven.com:8000"

[game.classes]
application = "dbat.game.application.Application"

[portal.classes]
application = "dbat.portal.application.Application"
login_parser = "dbat.portal.parsers.login.LoginParser"
user_parser = "dbat.portal.parsers.user.UserParser"
character_parser = "dbat.portal.parsers.character.CharacterParser"
admin_parser = "dbat.portal.parsers.admin.AdminParser"

[fastapi.routers]
auth = "dbat.rest.auth"
users = "dbat.rest.users"
characters = "dbat.rest.characters"
# Disabled
system = ""

[events]
circle = "dbat.events.circle"