dynaconf_merge = true

[mssp]
NAME = "Dragon Ball: Advent Truth"
CODEBASE = "CircleMUD"
FAMILY = "DikuMUD"

[portal.networking]
telnet = 1280
telnets = 1281
ssh = 1282
game_url = "https://dbat.mushhaven.com:8000"

[game.classes]
application = "dbat.game.application.Application"

[fastapi.routers]
auth = "dbat.rest.auth"
users = "dbat.rest.users"
# Disabled
characters = ""
system = ""