#!/bin/bash

# This script needs to run "./bin/circle", saving its .pid as server.pid in cwd.
# If circle exits and returns anything except a straight 0, then the process is restarted.

while true; do
    ./bin/circle > server.log < /dev/null
    exit_status=$?
    echo $! > server.pid
    if [ $exit_status -eq 0 ]; then
        exit 0
    fi
done