#pragma once
#include <cstdint>


enum class AffectFlag : std::uint8_t
{
    // dontuse          = 0,   // DON'T USE!
    blind = 1,           // (R) Char is blind
    invisible = 2,       // Char is invisible
    detect_align = 3,    // Char is sensitive to align
    detect_invis = 4,    // Char can see invis chars
    detect_magic = 5,    // Char is sensitive to magic
    sense_life = 6,      // Char can sense hidden life
    waterwalk = 7,       // Char can walk on water
    sanctuary = 8,       // Char protected by sanct.
    group = 9,           // (R) Char is grouped
    curse = 10,          // Char is cursed
    infravision = 11,    // Char can see in dark
    poison = 12,         // (R) Char is poisoned
    weakened_state = 13, // Char protected from evil?
    protect_good = 14,   // Char protected from good
    sleep = 15,          // (R) Char magically asleep
    no_track = 16,       // Char can't be tracked
    undead = 17,         // Char is undead
    paralyze = 18,       // Char is paralyzed
    sneak = 19,          // Char can move quietly
    hide = 20,           // Char is hidden
    // unused_20        = 21,  // Room for future expansion
    charm = 22,           // Char is charmed
    flying = 23,          // Char is flying
    water_breathing = 24, // Char can breathe non-O2
    angelic = 25,         // Char is an angelic being
    ethereal = 26,        // Char is ethereal
    magic_only = 27,      // Char only hurt by magic
    next_partial = 28,    // Next action cannot be full
    next_no_action = 29,  // Next action cannot attack
    stunned = 30,         // Char is stunned
    tamed = 31,           // Char has been tamed
    creeping_death = 32,  // Char is undergoing creeping death
    spirit = 33,          // Char has no body
    stoneskin = 34,       // Char has temporary DR
    summoned = 35,        // Char is summoned (transient)
    celestial = 36,       // Char is celestial
    fiendish = 37,        // Char is fiendish
    fire_shield = 38,     // Char has fire shield
    low_light = 39,       // Char has low light eyes
    zanzoken = 40,        // Char is ready to zanzoken
    knocked = 41,         // Char is knocked OUT
    might = 42,           // Strength +3
    flex = 43,            // Agility +3
    genius = 44,          // Intelligence +3
    bless = 45,           // Bless for better regen
    burnt = 46,           // Disintegrated corpse
    burned = 47,          // Burned by honoo or similar skill
    mbreak = 48,          // Can't charge while flagged
    hasshuken = 49,       // Does double punch damage
    future = 50,          // Future Sight
    paralyzed = 51,       // Real Paralyze
    infuse = 52,          // Ki-infused attacks
    enlighten = 53,       // Enlighten
    frozen = 54,          // They got frozededed
    fireshield = 55,      // They have a blazing personality
    ensnared = 56,        // Silk ensnaring their arms!
    hayasa = 57,          // They are speedy!
    pursuit = 58,         // Being followed
    wither = 59,          // Their body is withered
    hydrozap = 60,        // Custom Skill Kanso Suru
    position = 61,        // Better combat position
    psychic_shocked = 62, // Psychic Shock
    metamorph = 63,       // Metamorphosis
    healglow = 64,        // Healing Glow
    earmor = 65,          // Ethereal Armor
    echains = 66,         // Ethereal Chains
    wunjo_rune = 67,      // Wunjo rune
    purisaz_rune = 68,    // Purisaz rune
    ashed = 69,           // Leaves ash
    puked = 70,
    liquefied = 71,
    shell = 72,
    immunity = 73,
    spiritcontrol = 74,
    ginyu_pose = 75,
    kyodaika = 76,
    shadowstitch = 77,
    echains_debuff = 78,
    starphase = 79,
    mbreak_debuff = 80,
    limit_breaking = 81
};

/* Affect bits: used in Character.affected_by */
/* WARNING: In the world files, NEVER set the bits marked "R" ("Reserved") */
constexpr int AFF_DONTUSE = 0;         /* DON'T USE! 		*/
constexpr int AFF_BLIND = 1;           /* (R) Char is blind         */
constexpr int AFF_INVISIBLE = 2;       /* Char is invisible         */
constexpr int AFF_DETECT_ALIGN = 3;    /* Char is sensitive to align*/
constexpr int AFF_DETECT_INVIS = 4;    /* Char can see invis chars  */
constexpr int AFF_DETECT_MAGIC = 5;    /* Char is sensitive to magic*/
constexpr int AFF_SENSE_LIFE = 6;      /* Char can sense hidden life*/
constexpr int AFF_WATERWALK = 7;       /* Char can walk on water    */
constexpr int AFF_SANCTUARY = 8;       /* Char protected by sanct.  */
constexpr int AFF_GROUP = 9;           /* (R) Char is grouped       */
constexpr int AFF_CURSE = 10;          /* Char is cursed            */
constexpr int AFF_INFRAVISION = 11;    /* Char can see in dark      */
constexpr int AFF_POISON = 12;         /* (R) Char is poisoned      */
constexpr int AFF_WEAKENED_STATE = 13; /* Char protected from evil  */
constexpr int AFF_PROTECT_GOOD = 14;   /* Char protected from good  */
constexpr int AFF_SLEEP = 15;          /* (R) Char magically asleep */
constexpr int AFF_NOTRACK = 16;        /* Char can't be tracked     */
constexpr int AFF_UNDEAD = 17;         /* Char is undead 		*/
constexpr int AFF_PARALYZE = 18;       /* Char is paralized		*/
constexpr int AFF_SNEAK = 19;          /* Char can move quietly     */
constexpr int AFF_HIDE = 20;           /* Char is hidden            */
constexpr int AFF_UNUSED20 = 21;       /* Room for future expansion */
constexpr int AFF_CHARM = 22;          /* Char is charmed         	*/
constexpr int AFF_FLYING = 23;         /* Char is flying         	*/
constexpr int AFF_WATERBREATH = 24;    /* Char can breath non O2    */
constexpr int AFF_ANGELIC = 25;        /* Char is an angelic being  */
constexpr int AFF_ETHEREAL = 26;       /* Char is ethereal          */
constexpr int AFF_MAGICONLY = 27;      /* Char only hurt by magic   */
constexpr int AFF_NEXTPARTIAL = 28;    /* Next action cannot be full*/
constexpr int AFF_NEXTNOACTION = 29;   /* Next action cannot attack (took full action between rounds) */
constexpr int AFF_STUNNED = 30;        /* Char is stunned		*/
constexpr int AFF_TAMED = 31;          /* Char has been tamed	*/
constexpr int AFF_CDEATH = 32;         /* Char is undergoing creeping death */
constexpr int AFF_SPIRIT = 33;         /* Char has no body          */
constexpr int AFF_STONESKIN = 34;      /* Char has temporary DR     */
constexpr int AFF_SUMMONED = 35;       /* Char is summoned (i.e. transient */
constexpr int AFF_CELESTIAL = 36;      /* Char is celestial         */
constexpr int AFF_FIENDISH = 37;       /* Char is fiendish          */
constexpr int AFF_FIRE_SHIELD = 38;    /* Char has fire shield      */
constexpr int AFF_LOW_LIGHT = 39;      /* Char has low light eyes   */
constexpr int AFF_ZANZOKEN = 40;       /* Char is ready to zanzoken */
constexpr int AFF_KNOCKED = 41;        /* Char is knocked OUT!      */
constexpr int AFF_MIGHT = 42;          /* Strength +3               */
constexpr int AFF_FLEX = 43;           /* Agility +3                */
constexpr int AFF_GENIUS = 44;         /* Intelligence +3           */
constexpr int AFF_BLESS = 45;          /* Bless for better regen    */
constexpr int AFF_BURNT = 46;          /* Disintergrated corpse     */
constexpr int AFF_BURNED = 47;         /* Burned by honoo or similar skill */
constexpr int AFF_MBREAK = 48;         /* Can't charge while flagged */
constexpr int AFF_HASS = 49;           /* Does double punch damage  */
constexpr int AFF_FUTURE = 50;         /* Future Sight */
constexpr int AFF_PARA = 51;           /* Real Paralyze */
constexpr int AFF_INFUSE = 52;         /* Ki infused attacks */
constexpr int AFF_ENLIGHTEN = 53;      /* Enlighten */
constexpr int AFF_FROZEN = 54;         /* They got frozededed */
constexpr int AFF_FIRESHIELD = 55;     /* They have a blazing personality */
constexpr int AFF_ENSNARED = 56;       /* They have silk ensnaring their arms! */
constexpr int AFF_HAYASA = 57;         /* They are speedy!                */
constexpr int AFF_PURSUIT = 58;        /* Being followed */
constexpr int AFF_WITHER = 59;         /* Their body is withered */
constexpr int AFF_HYDROZAP = 60;       /* Custom Skill Kanso Suru */
constexpr int AFF_POSITION = 61;       /* Better combat position */
constexpr int AFF_SHOCKED = 62;        /* Psychic Shock          */
constexpr int AFF_METAMORPH = 63;      /* Metamorphisis, Demon's Ripoff Custom Skill */
constexpr int AFF_HEALGLOW = 64;       /* Healing Glow */
constexpr int AFF_EARMOR = 65;         /* Ethereal Armor */
constexpr int AFF_ECHAINS = 66;        /* Ethereal Chains */
constexpr int AFF_WUNJO = 67;          /* Wunjo rune */
constexpr int AFF_POTENT = 68;         /* Purisaz rune */
constexpr int AFF_ASHED = 69;          /* Leaves ash */
constexpr int AFF_PUKED = 70;
constexpr int AFF_LIQUEFIED = 71;
constexpr int AFF_SHELL = 72;
constexpr int AFF_IMMUNITY = 73;
constexpr int AFF_SPIRITCONTROL = 74;
constexpr int AFF_POSE = 75;
constexpr int AFF_KYODAIKA = 76;
constexpr int AFF_SHADOWSTITCH = 77;
constexpr int AFF_ECHAINS_DEBUFF = 78;
constexpr int AFF_STARPHASE = 79;
constexpr int AFF_MBREAK_DEBUFF = 80;
constexpr int AFF_LIMIT_BREAKING = 81;
