#pragma once

/* Let's define bonuses/negatives */
#define BONUS_THRIFTY           0
#define BONUS_PRODIGY           1
#define BONUS_QUICK_STUDY       2
#define BONUS_DIEHARD           3
#define BONUS_BRAWLER           4
#define BONUS_DESTROYER         5
#define BONUS_HARDWORKER        6
#define BONUS_HEALER            7
#define BONUS_LOYAL             8
#define BONUS_BRAWNY            9
#define BONUS_SCHOLARLY        10
#define BONUS_SAGE             11
#define BONUS_AGILE            12
#define BONUS_QUICK            13
#define BONUS_STURDY           14
#define BONUS_THICKSKIN        15
#define BONUS_RECIPE           16
#define BONUS_FIREPROOF        17
#define BONUS_POWERHIT         18
#define BONUS_HEALTHY          19
#define BONUS_INSOMNIAC        20
#define BONUS_EVASIVE          21
#define BONUS_WALL             22
#define BONUS_ACCURATE         23
#define BONUS_LEECH            24
#define BONUS_GMEMORY          25
#define BONUS_SOFT             26
#define BONUS_LATE             27
#define BONUS_IMPULSE          28
#define BONUS_SICKLY           29
#define BONUS_PUNCHINGBAG      30
#define BONUS_PUSHOVER         31
#define BONUS_POORDEPTH        32
#define BONUS_THINSKIN         33
#define BONUS_FIREPRONE        34
#define BONUS_INTOLERANT       35
#define BONUS_COWARD           36
#define BONUS_ARROGANT         37
#define BONUS_UNFOCUSED        38
#define BONUS_SLACKER          39
#define BONUS_SLOW_LEARNER     40
#define BONUS_MASOCHISTIC      41
#define BONUS_MUTE             42
#define BONUS_WIMP             43
#define BONUS_DULL             44
#define BONUS_FOOLISH          45
#define BONUS_CLUMSY           46
#define BONUS_SLOW             47
#define BONUS_FRAIL            48
#define BONUS_SADISTIC         49
#define BONUS_LONER            50
#define BONUS_BMEMORY          51

#define MAX_BONUSES            52