#pragma once

/* Some different kind of liquids for use in values of drink containers */
#define LIQ_WATER      0
#define LIQ_BEER       1
#define LIQ_WINE       2
#define LIQ_ALE        3
#define LIQ_DARKALE    4
#define LIQ_WHISKY     5
#define LIQ_LEMONADE   6
#define LIQ_FIREBRT    7
#define LIQ_LOCALSPC   8
#define LIQ_SLIME      9
#define LIQ_MILK       10
#define LIQ_TEA        11
#define LIQ_COFFE      12
#define LIQ_BLOOD      13
#define LIQ_SALTWATER  14
#define LIQ_CLEARWATER 15

#define NUM_LIQ_TYPES 16

#define MATERIAL_BONE           0
#define MATERIAL_CERAMIC        1
#define MATERIAL_COPPER         2
#define MATERIAL_DIAMOND        3
#define MATERIAL_GOLD           4
#define MATERIAL_IRON           5
#define MATERIAL_LEATHER        6
#define MATERIAL_MITHRIL        7
#define MATERIAL_OBSIDIAN       8
#define MATERIAL_STEEL          9
#define MATERIAL_STONE          10
#define MATERIAL_SILVER         11
#define MATERIAL_WOOD           12
#define MATERIAL_GLASS          13
#define MATERIAL_ORGANIC        14
#define MATERIAL_CURRENCY       15
#define MATERIAL_PAPER          16
#define MATERIAL_COTTON         17
#define MATERIAL_SATIN          18
#define MATERIAL_SILK           19
#define MATERIAL_BURLAP         20
#define MATERIAL_VELVET         21
#define MATERIAL_PLATINUM       22
#define MATERIAL_ADAMANTINE     23
#define MATERIAL_WOOL           24
#define MATERIAL_ONYX           25
#define MATERIAL_IVORY          26
#define MATERIAL_BRASS          27
#define MATERIAL_MARBLE         28
#define MATERIAL_BRONZE         29
#define MATERIAL_KACHIN         30
#define MATERIAL_RUBY           31
#define MATERIAL_SAPPHIRE       32
#define MATERIAL_EMERALD        33
#define MATERIAL_GEMSTONE       34
#define MATERIAL_GRANITE        35
#define MATERIAL_ENERGY         36
#define MATERIAL_HEMP           37
#define MATERIAL_CRYSTAL        38
#define MATERIAL_EARTH  	39
#define MATERIAL_LIQUID  	40
#define MATERIAL_CLOTH  	41
#define MATERIAL_METAL  	42
#define MATERIAL_WAX	  	43
#define MATERIAL_OTHER	  	44
#define MATERIAL_FOOD	  	45
#define MATERIAL_OIL	  	46

#define NUM_MATERIALS           47