#pragma once

#define SHADOW_DRAGON1_VNUM 81
#define SHADOW_DRAGON2_VNUM 82
#define SHADOW_DRAGON3_VNUM 83
#define SHADOW_DRAGON4_VNUM 84
#define SHADOW_DRAGON5_VNUM 85
#define SHADOW_DRAGON6_VNUM 86
#define SHADOW_DRAGON7_VNUM 87