#pragma once
#include "templates.h"

enum class ResetCommandType : uint8_t {
    MOB = 0,
    OBJ = 1,
    GIVE = 2,
    PUT = 3,
    GET = 4,
    EQUIP = 5,
    DOOR = 6,
    REMOVE = 7,
    TRIGGER = 8,
    VARIABLE = 9
};

struct SpawnRegistry {
    std::unordered_map<vnum, std::vector<std::weak_ptr<Character>>> mobiles;
    std::unordered_map<vnum, std::vector<std::weak_ptr<Object>>> objects;
    std::weak_ptr<Object> lastObj;
    std::weak_ptr<Character> lastChar;
};

struct ResetCommand {
    ResetCommandType type;  /* Type of reset command */
    bool if_flag{false};         /* If TRUE: execute only if preceding executed */
    int target{NOTHING}; // vnum for spawning mob/obj/trigger, direction for door
    // The maximum amount of things generated by this spawn rule. used for MOB/OBJ. 0 disables check.
    int max{0};            
    // for MOB/OBJ, will not spawn if x amount already in location. 0 disables check.
    // ALso used for T type with Room targets.
    int max_location{0};       
    int ex{0};             // Flags for D, or TriggerType for T/V. Equip slot for EQUIP
    int chance{100};             // Chance of this happening. Not always used.
    std::string key, value; // used for VARIABLE.

    bool executeAt(Location& loc, SpawnRegistry &reg) const;

    std::string print() const;
};

template <>
struct fmt::formatter<ResetCommand> {
    constexpr auto parse(format_parse_context& ctx) { return ctx.begin(); }

    template <typename FormatContext>
    auto format(const ResetCommand& z, FormatContext& ctx) {
        return fmt::format_to(ctx.out(), "{}", z.print());
    }
};

struct HasResetCommands {
    std::vector<ResetCommand> resetCommands;
    std::string printResetCommands() const;
};

extern Result<ResetCommand> parseResetCommand(std::vector<std::string> seq);