#pragma once
#include <vector>
#include <unordered_map>
#include <memory>

#include "Typedefs.h"
#include "Result.h"

struct Character;
struct Object;
struct Location;

enum class ResetCommandType : uint8_t {
    MOB = 0,
    OBJ = 1,
    GIVE = 2,
    PUT = 3,
    EQUIP = 4,
    DOOR = 5,
    REMOVE = 6,
    TRIGGER = 7,
    VARIABLE = 8
};

struct SpawnRegistry {
    std::unordered_map<vnum, std::vector<std::weak_ptr<Character>>> mobiles;
    std::unordered_map<vnum, std::vector<std::weak_ptr<Object>>> objects;
    std::weak_ptr<Object> lastObj;
    std::weak_ptr<Character> lastChar;
};

struct ResetCommand {
    ResetCommandType type;  /* Type of reset command */
    bool if_flag{false};         /* If TRUE: execute only if preceding executed */
    int target{-1}; // vnum for spawning mob/obj/trigger, direction for door
    // The maximum amount of things generated by this spawn rule. used for MOB/OBJ. 0 disables check.
    int max{0};            
    // for MOB/OBJ, will not spawn if x amount already in location. 0 disables check.
    // ALso used for T type with Room targets.
    int max_location{0};       
    int ex{0};             // Flags for D, or TriggerType for T/V. Equip slot for EQUIP
    int chance{100};             // Chance of this happening. Not always used.
    std::string key, value; // used for VARIABLE.

    bool executeAt(Location& loc, SpawnRegistry &reg) const;

    std::string print() const;
};

inline std::string format_as(const ResetCommand& cmd) {
    return cmd.print();
}


struct HasResetCommands {
    std::vector<ResetCommand> resetCommands;
    std::string printResetCommands() const;
};

inline std::string format_as(const HasResetCommands& hrc) {
    return hrc.printResetCommands();
}

extern Result<ResetCommand> parseResetCommand(std::vector<std::string> seq);