dynaconf_merge = true

[game]
# The class to use for the game application. Generally no reason to change this.
class = "muforge.game:Application"

[game.webserver]
# The address to bind the webserver to.
bind_address = "0.0.0.0"
# The port to bind the webserver to.
port = 8000
# Whether to use TLS for the webserver. It is HIGHLY RECOMMENDED to use TLS.
tls = true
# A list of trusted proxy IPs. Used for detecting the client's real IP address.
# IE: X-Forwarded-For headers will be trusted if the proxy's IP is in this list.
trusted_proxy_ips = ["127.0.0.1"]
