dynaconf_merge = true

[muforge]
# The name of the project / game. Replace it with your own.
name = "muforge"
# The class to use for the launcher.
launcher = "muforge.launcher:Launcher"

# The plugins to load. This is a list of python module:property paths.
# Core is basically built-in and required by all other muforge plugins.
plugins = ["muplugins:Core", "muplugins:Telnet", "dbat:DBAT"]

[tls]
# The paths to TLS cert and key the whole application should use for any listeners that
# want TLS.
certificate = "localhost.pem"
key = "localhost-key.pem"
