dynaconf_merge = true

[plugin.telnet]
# How many bytes can be in the application buffer before the connection is closed.
application_buffer_size = 16384
# For IAC SC <option> <data> IAC SE sub-negotiation, how many bytes can be in the <data> buffer
# Anything over this will result in connection closure.
subnegotiate_buffer_size = 16384
# Send an IAC NOP every N seconds to keep the connection alive.
# This will only be sent if a client engaged in any sort of telnet negotiation.
# Disabled if <=0
keepalive_interval = 30

# Warn clients on connect if they don't support telnet.
warn_no_telnet = true
# If the warning is shown, recommend these clients to the user.
recommended_clients = ["MUSHClient", "BeipMU", "TinTin++", "MUDlet"]
# Which color mode to use for telnet clients by default, if not altered by MTTS.
# supported values: 0, 1, 2, 3, for none, ansi16, xterm256, and truecolor respectively
color_mode = 1

# the adapter and port to use for plain telnet.
[plugin.telnet.telnet]
bind_address = "0.0.0.0"
port = 7000

# the adapter and port to use for TLS enhanced telnet.
# It will use the same TLS config as the web server.
# If TLS isn't enabled, this will be ignored.
[plugin.telnet.telnets]
bind_address = "0.0.0.0"
port = 7001

[plugin.telnet.mssp]
# the following values will fill the MSSP (MUD Server Status Protocol)
# dictionary that's sent to clients that request it.
# Reference: https://mudstandards.org/mud/mssp
#
# MuForge will attempt to fill in dynamic values like PLAYERS from the game's state,
# and NAME, PORT, SSL, etc, from other config sources.
# All key-value pairs present below will override any generated values.

# NAME will be taken from the muforge config unless overridden here.
# NAME = "muforge"
"CRAWL DELAY" = -1
