dynaconf_merge = true

[plugin.core.jwt]
# These are the defaults for the JWT tokens.
# PLEASE CHANGE THE SECRET!
algorithm = "HS256"
secret = "CHANGE_ME_DAMMIT"
token_expire_minutes = 30
# 7 days in minutes.
refresh_expire_minutes = 10080

[plugin.core.crypt]
# these key-values are passed verbatim to passlib.contxt.CryptContext()
schemes = ["argon2", "sha512_crypt", "plaintext"]
deprecated = ["sha512_crypt", "plaintext"]

[plugin.core.postgresql]
# The information that'll be fed straight into
# asyncpg's connection function via **kwargs.
# The dsn format is: postgresql://<user>:<password>@<host>:<port>/<database>
dsn = "postgres://muforge:muforge@localhost:5432/muforge"
