#pragma once
#include <cstdint>


enum class AffectFlag : std::uint8_t
{
    // dontuse          = 0,   // DON'T USE!
    blind = 1,           // (R) Char is blind
    invisible = 2,       // Char is invisible
    detect_align = 3,    // Char is sensitive to align
    detect_invis = 4,    // Char can see invis chars
    detect_magic = 5,    // Char is sensitive to magic
    sense_life = 6,      // Char can sense hidden life
    waterwalk = 7,       // Char can walk on water
    sanctuary = 8,       // Char protected by sanct.
    group = 9,           // (R) Char is grouped
    curse = 10,          // Char is cursed
    infravision = 11,    // Char can see in dark
    poison = 12,         // (R) Char is poisoned
    weakened_state = 13, // Char protected from evil?
    protect_good = 14,   // Char protected from good
    sleep = 15,          // (R) Char magically asleep
    no_track = 16,       // Char can't be tracked
    undead = 17,         // Char is undead
    paralyze = 18,       // Char is paralyzed
    sneak = 19,          // Char can move quietly
    hide = 20,           // Char is hidden
    // unused_20        = 21,  // Room for future expansion
    charm = 22,           // Char is charmed
    flying = 23,          // Char is flying
    water_breathing = 24, // Char can breathe non-O2
    angelic = 25,         // Char is an angelic being
    ethereal = 26,        // Char is ethereal
    magic_only = 27,      // Char only hurt by magic
    next_partial = 28,    // Next action cannot be full
    next_no_action = 29,  // Next action cannot attack
    stunned = 30,         // Char is stunned
    tamed = 31,           // Char has been tamed
    creeping_death = 32,  // Char is undergoing creeping death
    spirit = 33,          // Char has no body
    stoneskin = 34,       // Char has temporary DR
    summoned = 35,        // Char is summoned (transient)
    celestial = 36,       // Char is celestial
    fiendish = 37,        // Char is fiendish
    fire_shield = 38,     // Char has fire shield
    low_light = 39,       // Char has low light eyes
    zanzoken = 40,        // Char is ready to zanzoken
    knocked = 41,         // Char is knocked OUT
    might = 42,           // Strength +3
    flex = 43,            // Agility +3
    genius = 44,          // Intelligence +3
    bless = 45,           // Bless for better regen
    burnt = 46,           // Disintegrated corpse
    burned = 47,          // Burned by honoo or similar skill
    mbreak = 48,          // Can't charge while flagged
    hasshuken = 49,       // Does double punch damage
    future = 50,          // Future Sight
    paralyzed = 51,       // Real Paralyze
    infuse = 52,          // Ki-infused attacks
    enlighten = 53,       // Enlighten
    frozen = 54,          // They got frozededed
    fireshield = 55,      // They have a blazing personality
    ensnared = 56,        // Silk ensnaring their arms!
    hayasa = 57,          // They are speedy!
    pursuit = 58,         // Being followed
    wither = 59,          // Their body is withered
    hydrozap = 60,        // Custom Skill Kanso Suru
    position = 61,        // Better combat position
    psychic_shocked = 62, // Psychic Shock
    metamorph = 63,       // Metamorphosis
    healglow = 64,        // Healing Glow
    earmor = 65,          // Ethereal Armor
    echains = 66,         // Ethereal Chains
    wunjo_rune = 67,      // Wunjo rune
    purisaz_rune = 68,    // Purisaz rune
    ashed = 69,           // Leaves ash
    puked = 70,
    liquefied = 71,
    shell = 72,
    immunity = 73,
    spiritcontrol = 74,
    ginyu_pose = 75,
    kyodaika = 76,
    shadowstitch = 77,
    echains_debuff = 78,
    starphase = 79,
    mbreak_debuff = 80,
    limit_breaking = 81
};

/* Affect bits: used in Character.affected_by */
/* WARNING: In the world files, NEVER set the bits marked "R" ("Reserved") */
constexpr int AFF_DONTUSE = 0;         /* DON'T USE! 		*/
constexpr AffectFlag AFF_BLIND = AffectFlag::blind;           /* (R) Char is blind         */
constexpr AffectFlag AFF_INVISIBLE = AffectFlag::invisible;       /* Char is invisible         */
constexpr AffectFlag AFF_DETECT_ALIGN = AffectFlag::detect_align;    /* Char is sensitive to align*/
constexpr AffectFlag AFF_DETECT_INVIS = AffectFlag::detect_invis;    /* Char can see invis chars  */
constexpr AffectFlag AFF_DETECT_MAGIC = AffectFlag::detect_magic;    /* Char is sensitive to magic*/
constexpr AffectFlag AFF_SENSE_LIFE = AffectFlag::sense_life;      /* Char can sense hidden life*/
constexpr AffectFlag AFF_WATERWALK = AffectFlag::waterwalk;       /* Char can walk on water    */
constexpr AffectFlag AFF_SANCTUARY = AffectFlag::sanctuary;       /* Char protected by sanct.  */
constexpr AffectFlag AFF_GROUP = AffectFlag::group;           /* (R) Char is grouped       */
constexpr AffectFlag AFF_CURSE = AffectFlag::curse;          /* Char is cursed            */
constexpr AffectFlag AFF_INFRAVISION = AffectFlag::infravision;    /* Char can see in dark      */
constexpr AffectFlag AFF_POISON = AffectFlag::poison;         /* (R) Char is poisoned      */
constexpr AffectFlag AFF_WEAKENED_STATE = AffectFlag::weakened_state; /* Char protected from evil  */
constexpr AffectFlag AFF_PROTECT_GOOD = AffectFlag::protect_good;   /* Char protected from good  */
constexpr AffectFlag AFF_SLEEP = AffectFlag::sleep;          /* (R) Char magically asleep */
constexpr AffectFlag AFF_NOTRACK = AffectFlag::no_track;        /* Char can't be tracked     */
constexpr AffectFlag AFF_UNDEAD = AffectFlag::undead;         /* Char is undead 		*/
constexpr AffectFlag AFF_PARALYZE = AffectFlag::paralyze;       /* Char is paralized		*/
constexpr AffectFlag AFF_SNEAK = AffectFlag::sneak;          /* Char can move quietly     */
constexpr AffectFlag AFF_HIDE = AffectFlag::hide;           /* Char is hidden            */

constexpr AffectFlag AFF_CHARM = AffectFlag::charm;          /* Char is charmed         	*/
constexpr AffectFlag AFF_FLYING = AffectFlag::flying;         /* Char is flying         	*/
constexpr AffectFlag AFF_WATERBREATH = AffectFlag::water_breathing;    /* Char can breath non O2    */
constexpr AffectFlag AFF_ANGELIC = AffectFlag::angelic;        /* Char is an angelic being  */
constexpr AffectFlag AFF_ETHEREAL = AffectFlag::ethereal;       /* Char is ethereal          */
constexpr AffectFlag AFF_MAGICONLY = AffectFlag::magic_only;      /* Char only hurt by magic   */
constexpr AffectFlag AFF_NEXTPARTIAL = AffectFlag::next_partial;    /* Next action cannot be full*/
constexpr AffectFlag AFF_NEXTNOACTION = AffectFlag::next_no_action;   /* Next action cannot attack (took full action between rounds) */
constexpr AffectFlag AFF_STUNNED = AffectFlag::stunned;        /* Char is stunned		*/
constexpr AffectFlag AFF_TAMED = AffectFlag::tamed;          /* Char has been tamed	*/
constexpr AffectFlag AFF_CDEATH = AffectFlag::creeping_death;         /* Char is undergoing creeping death */
constexpr AffectFlag AFF_SPIRIT = AffectFlag::spirit;         /* Char has no body          */
constexpr AffectFlag AFF_STONESKIN = AffectFlag::stoneskin;      /* Char has temporary DR     */
constexpr AffectFlag AFF_SUMMONED = AffectFlag::summoned;       /* Char is summoned (i.e. transient */
constexpr AffectFlag AFF_CELESTIAL = AffectFlag::celestial;      /* Char is celestial         */
constexpr AffectFlag AFF_FIENDISH = AffectFlag::fiendish;       /* Char is fiendish          */
constexpr AffectFlag AFF_FIRE_SHIELD = AffectFlag::fire_shield;    /* Char has fire shield      */
constexpr AffectFlag AFF_LOW_LIGHT = AffectFlag::low_light;      /* Char has low light eyes   */
constexpr AffectFlag AFF_ZANZOKEN = AffectFlag::zanzoken;       /* Char is ready to zanzoken */
constexpr AffectFlag AFF_KNOCKED = AffectFlag::knocked;        /* Char is knocked OUT!      */
constexpr AffectFlag AFF_MIGHT = AffectFlag::might;          /* Strength +3               */
constexpr AffectFlag AFF_FLEX = AffectFlag::flex;           /* Agility +3                */
constexpr AffectFlag AFF_GENIUS = AffectFlag::genius;         /* Intelligence +3           */
constexpr AffectFlag AFF_BLESS = AffectFlag::bless;          /* Bless for better regen    */
constexpr AffectFlag AFF_BURNT = AffectFlag::burnt;          /* Disintergrated corpse     */
constexpr AffectFlag AFF_BURNED = AffectFlag::burned;         /* Burned by honoo or similar skill */
constexpr AffectFlag AFF_MBREAK = AffectFlag::mbreak;         /* Can't charge while flagged */
constexpr AffectFlag AFF_HASS = AffectFlag::hasshuken;           /* Does double punch damage  */
constexpr AffectFlag AFF_FUTURE = AffectFlag::future;         /* Future Sight */
constexpr AffectFlag AFF_PARA = AffectFlag::paralyzed;           /* Real Paralyze */
constexpr AffectFlag AFF_INFUSE = AffectFlag::infuse;         /* Ki infused attacks */
constexpr AffectFlag AFF_ENLIGHTEN = AffectFlag::enlighten;      /* Enlighten */
constexpr AffectFlag AFF_FROZEN = AffectFlag::frozen;         /* They got frozededed */
constexpr AffectFlag AFF_FIRESHIELD = AffectFlag::fire_shield;     /* They have a blazing personality */
constexpr AffectFlag AFF_ENSNARED = AffectFlag::ensnared;       /* They have silk ensnaring their arms! */
constexpr AffectFlag AFF_HAYASA = AffectFlag::hayasa;         /* They are speedy!                */
constexpr AffectFlag AFF_PURSUIT = AffectFlag::pursuit;        /* Being followed */
constexpr AffectFlag AFF_WITHER = AffectFlag::wither;         /* Their body is withered */
constexpr AffectFlag AFF_HYDROZAP = AffectFlag::hydrozap;       /* Custom Skill Kanso Suru */
constexpr AffectFlag AFF_POSITION = AffectFlag::position;       /* Better combat position */
constexpr AffectFlag AFF_SHOCKED = AffectFlag::psychic_shocked;        /* Psychic Shock          */
constexpr AffectFlag AFF_METAMORPH = AffectFlag::metamorph;      /* Metamorphisis, Demon's Ripoff Custom Skill */
constexpr AffectFlag AFF_HEALGLOW = AffectFlag::healglow;       /* Healing Glow */
constexpr AffectFlag AFF_EARMOR = AffectFlag::earmor;         /* Ethereal Armor */
constexpr AffectFlag AFF_ECHAINS = AffectFlag::echains;        /* Ethereal Chains */
constexpr AffectFlag AFF_WUNJO = AffectFlag::wunjo_rune;          /* Wunjo rune */
constexpr AffectFlag AFF_POTENT = AffectFlag::purisaz_rune;         /* Purisaz rune */
constexpr AffectFlag AFF_ASHED = AffectFlag::ashed;          /* Leaves ash */
constexpr AffectFlag AFF_PUKED = AffectFlag::puked;
constexpr AffectFlag AFF_LIQUEFIED = AffectFlag::liquefied;
constexpr AffectFlag AFF_SHELL = AffectFlag::shell;
constexpr AffectFlag AFF_IMMUNITY = AffectFlag::immunity;
constexpr AffectFlag AFF_SPIRITCONTROL = AffectFlag::spiritcontrol;
constexpr AffectFlag AFF_POSE = AffectFlag::ginyu_pose;
constexpr AffectFlag AFF_KYODAIKA = AffectFlag::kyodaika;
constexpr AffectFlag AFF_SHADOWSTITCH = AffectFlag::shadowstitch;
constexpr AffectFlag AFF_ECHAINS_DEBUFF = AffectFlag::echains_debuff;
constexpr AffectFlag AFF_STARPHASE = AffectFlag::starphase;
constexpr AffectFlag AFF_MBREAK_DEBUFF = AffectFlag::mbreak_debuff;
constexpr AffectFlag AFF_LIMIT_BREAKING = AffectFlag::limit_breaking;
